name: 'test Revert Last Merge'
description: 'Revert Last Merge test'

branding:
  icon: "aperture"
  color: "purple"

inputs: 
  BRANCH_NAME:
    description: 'tet Revert Last Merge test'
    required: false
    default: 'master'

runs:
  using: 'docker'
  image: 'Dockerfile'
